[update] docker-texcmd

diff --git a/bin/docker-texcmd b/bin/docker-texcmd
--- a/bin/docker-texcmd
+++ b/bin/docker-texcmd
@@ -16,8 +16,8 @@ fi
 
 # Check whether option is given
 if [[ -z "$@" ]]; then
-  echo "ERROR: Specify more than one option."
-  echo "See '$0 --help'."
+  echo "ERROR: Specify more than one option." >&2
+  echo "See '$CMD_NAME --help'." >&2
   exit 1
 fi
 
