[update] done macOS setup

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -1,3 +1,39 @@
-#!/bin/bash
+#!/bin/sh
 
-echo 'Hello, world!'
+################################################################################
+# VARIABLES                                                                    #
+DOTFILES_REPOS="https://github.com/h-matsuo/dotfiles.git"
+DOTFILES_DIR="${HOME}/.dotfiles"; export DOTFILES_DIR
+DOTFILES_DESC='
+       _       _    __ _ _
+    __| | ___ | |_ / _(_) | ___  ___
+   / _` |/ _ \| __| |_| | |/ _ \/ __|
+  | (_| | (_) | |_|  _| | |  __/\__ \
+   \__,_|\___/ \__|_| |_|_|\___||___/
+
+  This script will automatically setup your development environment.
+
+  Copyright (c) 2018 Hiroyuki Matsuo.
+'
+################################################################################
+
+# Check whether git command exists
+if ! type git >/dev/null 2>&1; then
+  echo "ERROR: Please install git command then re-run this script." >&2
+  exit 1
+fi
+
+# Print description
+echo "$DOTFILES_DESC"
+
+# Change working directory
+cd $(dirname "$DOTFILES_DIR")
+
+# Git clone dotfiles repository
+git clone --recursive "$DOTFILES_REPOS" $(basename "$DOTFILES_DIR")
+
+# Change working directory
+cd $(basename "$DOTFILES_DIR")
+
+# Run etc/setup.sh
+. etc/setup.sh
